# Generated by Django 4.0.3 on 2022-04-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('imageName', models.CharField(max_length=30)),
                ('imageCaption', models.TextField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
