# Generated by Django 4.0.3 on 2022-04-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
    ]
