# Generated by Django 4.0.3 on 2022-04-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
